-- Add a new table for nurse data
CREATE TABLE IF NOT EXISTS nurse_data (
    MedicalP_ID INT PRIMARY KEY AUTO_INCREMENT,
    CitizenI_Num VARCHAR(20) NOT NULL,
    ProfessionalM_license_Num VARCHAR(20) NOT NULL,
    Firstname VARCHAR(255) NOT NULL,
    Lastname VARCHAR(255) NOT NULL,
    Birthday DATE NOT NULL,
    Position VARCHAR(50) NOT NULL,
    Ward_ID INT,
    Employment_Year INT,
    hospital_code INT,
    Salary DECIMAL(10, 2),
    Gender VARCHAR(10) NOT NULL,
    Phone_Number VARCHAR(15),
    Number_Children INT,
    MaritalS_ID INT,
    Religion VARCHAR(50),
    Email VARCHAR(255),
    Line_ID VARCHAR(255),
    RelativeP_Num VARCHAR(15),
    Village VARCHAR(255),
    House_number VARCHAR(20),
    Zip_Code VARCHAR(10),
    Province VARCHAR(255),
    District VARCHAR(255),
    Subdistrict VARCHAR(255),
    FOREIGN KEY (Ward_ID) REFERENCES ward_data(Ward_ID),
    FOREIGN KEY (hospital_code) REFERENCES hospitals(hospital_code),
);

-- Sample data for initial testing
INSERT INTO nurse_data (
    CitizenI_Num,
    ProfessionalM_license_Num,
    Firstname,
    Lastname,
    Birthday,
    Position,
    Ward_ID,
    Employment_Year,
    hospital_code,
    Salary,
    Gender,
    Phone_Number,
    Number_Children,
    MaritalS_ID,
    Religion,
    Email,
    Line_ID,
    RelativeP_Num,
    Village,
    House_number,
    Zip_Code,
    Province,
    District,
    Subdistrict
) VALUES (
    '1234567890123',
    '7890123456',
    'John',
    'Doe',
    '1990-01-01',
    'Registered Nurse',
    1,
    5,
    1,
    50000.00,
    'Male',
    '123456789',
    2,
    1,
    'Christian',
    'john.doe@example.com',
    'john_doe_line',
    '987654321',
    'Village A',
    '123',
    '12345',
    'Province A',
    'District A',
    'Subdistrict A'
    
);
