INSERT INTO `Nurses` (
    MedicalP_ID,
    CitizenI_Num,
    ProfessionalM_license_Num,
    Firstname,
    Lastname,
    Birthday,
    Position,
    WardID,
    Employment_Year,
    HospitalID,
    Salary,
    Gender,
    Phone_Number,
    Number_Children,
    MaritalS_ID,
    Religion,
    Email,
    Line_ID,
    RelativeP_Num,
    Village,
    House_number,
    Zip_Code,
    Province,
    District,
    Subdistrict
) VALUES (
    1,
    '1234567890123',
    '7890123456',
    'อรพรรณ',
    'กันทะวงศ์',
    '1990-01-01',
    'Nurse',
    1,
    5,
    1,
    50000.00,
    'Male',
    '123456789',
    2,
    1,
    'Christian',
    'john.doe@example.com',
    'john_doe_line',
    '987654321',
    'Village A',
    '123',
    '12345',
    'Province A',
    'District A',
    'Subdistrict A'
);
