-- Active: 1701774805198@@127.0.0.1@8889@NursePlan
CREATE Table Plantype (
    id INT AUTO_INCREMENT PRIMARY KEY,
    TypeName VARCHAR(10) NOT NULL,
    Morning BOOLEAN,
    Afternoon BOOLEAN,
    Night BOOLEAN,
    X BOOLEAN,
    V BOOLEAN,
    Nleave BOOLEAN,
    C BOOLEAN,
    Part BOOLEAN,
    OtM BOOLEAN,
    OtA BOOLEAN,
    OtN BOOLEAN,
    StatusS BOOLEAN,
    StatusOt12 BOOLEAN,
    StatusOt8 BOOLEAN,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    DeletedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);